name: Project Automation

on:
  issues:
    types: [opened, edited]
  create:
    branches:
      - '**'
  pull_request:
    types: [opened, closed, edited]

jobs:
  backlog:
    if: github.event_name == 'issues' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Add new issue to "Backlog"
        uses: docker://takanabe/github-actions-automate-projects:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/orgs/UOWD-Tech-Club/projects/2
          GITHUB_PROJECT_COLUMN_NAME: Backlog
      - name: Add "Available" label to the issue
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
            -f labels='["Status: Available"]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
